App:
  AttachmentIncomeRate: 0.8
  MaxCommentCount: 10
  DefaultContextTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
Server:
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8010
  ReadTimeout: 60
  WriteTimeout: 60
Features:
  Default: [ "SimpleCacheIndex", "Zinc", "LoggerZinc" ]
  Develop: [ "BigCacheIndex", "Meili", "LoggerMeili" ]
  Demo: [ "SimpleCacheIndex", "Zinc", "LoggerFile" ]
CacheIndex:
  MaxUpdateQPS: 100             # QPS of max add/remove/update Post, set range [10, 10000], default 100
SimpleCacheIndex:
  MaxIndexSize: 200
  CheckTickDuration: 60
  ExpireTickDuration: 300
BigCacheIndex:
  MaxIndexPage: 1024
  Verbose: False
  ExpireInSecond: 300
Logger:
  Level: debug #  panic|fatal|error|warn|info|debug|trace
LoggerFile:
  SavePath: data/logs
  FileName: app
  FileExt: .log
LoggerZinc:
  Host: 192.168.100.250:4080
  Index: dao-log
  User: admin
  Password: admin
  Secure: False
LoggerMeili:
  Host: meili:7700
  Index: dao-log
  ApiKey: dao-meilisearch
  Secure: False
  MinWorker: 5               # Minimum background worker, set range [5, 100], default 5
  MaxLogBuffer: 100          # Max log cache entries, set in the range [10, 10000], default 100
TweetSearch:
  MaxUpdateQPS: 100            # QPS of Max Add/Remove/Update Post, setting range [10, 10000], default 100
  MinWorker: 10                # Minimum background update worker, set range [5, 1000], default 10
Zinc:
  Host: 192.168.100.250:4080
  Index: dao-data
  User: admin
  Password: admin
  Secure: False
Meili:
  Host: meili:7700
  Index: dao-data
  ApiKey: dao-meilisearch
  Secure: False
MongoDB:
  Username:
  Password:
  Host: 192.168.100.250:21718
  DBName: dao
Redis:
  Host: 192.168.100.250:63091
  Password: redis
  DB: 1
Eth:
  Endpoint: "https://node.wallet.unipass.id/polygon-mumbai"